version: '3'
services:
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=0721
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - springboot

  appservice:
    build: ./boot
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/springboot?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=****
    ports:
      - 8080:8080
    networks:
      - springboot

networks:
  springboot:
